package EventsAlerts;

public enum InfoType {
    animalSound,
    applianceUsage,
    sportEquipmentUsage,
    extinguishingFire,
    callingFireman,
    cheeringUpChild,
    drivingCar,
    repairingAppliance,
    hangingOn,
    workingOnPC,
    eatFood,
    fillingFood,
    watchingTV,
    turningOffAppliance,
    turningOnAppliance,
    turningIdleAppliance,
    goingShopping,
    pullingBlind,
    insertingCD,
    ejectingCD,
    playingCD,
    fillingWithLaundry,
    cycleStart,
    cycleFinish,
    takingOutLaundry,
    thermostatStrategy,
    temperatureChange
}
